# -*- text -*-
##
## radiusd.conf -- FreeRADIUS Master Configuration for EMMATECH Multi-Tenant Billing
##

prefix = /usr
exec_prefix = /usr
sysconfdir = /etc
localstatedir = /var
sbindir = ${exec_prefix}/sbin
logdir = /var/log/freeradius
raddbdir = /etc/freeradius/3.0
radacctdir = ${logdir}/radacct

name = freeradius

# Standard directories
confdir = ${raddbdir}
modconfdir = ${confdir}/mods-config
certdir = ${confdir}/certs
cadir   = ${confdir}/certs
run_dir = ${localstatedir}/run/${name}

db_dir = ${localstatedir}/lib/freeradius
libdir = /usr/lib/freeradius
shlibdir = ${libdir}

max_request_time = 30
cleanup_delay = 5
max_requests = 16384
hostname_lookups = no

log {
	destination = stdout
	colourise = yes
	file = ${logdir}/radius.log
	syslog_facility = daemon
	stripped_names = no
	auth = yes
	auth_badpass = yes
	auth_goodpass = yes
	msg_denied = "You are not authorized to access this service."
}

security {
	user = freerad
	group = freerad
	allow_core_dumps = no
	max_attributes = 200
	reject_delay = 1
	status_server = yes
}

# Load master dictionary and dynamic clients configuration
$INCLUDE dictionary
$INCLUDE clients.conf

# Modules and Sites
modules {
    sql {
        driver = "rlm_sql_postgresql"
        server = "${env:POSTGRES_HOST}"
        port = "${env:POSTGRES_PORT}"
        login = "${env:POSTGRES_USER}"
        password = "${env:POSTGRES_PASSWORD}"
        radius_db = "${env:POSTGRES_DB}"
    }
	$INCLUDE mods-enabled/
}

# Virtual servers
$INCLUDE sites-enabled/
