# This is a minimal configuration for RadSec.
# You MUST ensure it includes necessary client/database configs 
# from the default FreeRADIUS installation.

listen {
    type = auth
    ipaddr = *
    port = 2083
    proto = tcp
    tls = yes
    
    # Paths must match where Certbot places them
    certdir = /etc/letsencrypt/live/${RADIUS_DOMAIN}/
    ca_file = ${certdir}/chain.pem
    private_key_file = ${certdir}/privkey.pem
    certificate_file = ${certdir}/fullchain.pem
}
