sql {
    driver = "rlm_sql_postgresql"
    server = "${env:DB_HOST}"
    port = 5432
    login = "${env:DB_USER}"
    password = "${env:DB_PASSWORD}"
    radius_db = "${env:DB_NAME}"

    authorize_check_query = "SELECT id, username, attribute, value, op FROM radcheck WHERE username = '%{SQL-User-Name}'"
    authorize_reply_query = "SELECT id, username, attribute, value, op FROM radreply WHERE username = '%{SQL-User-Name}'"
}
