/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDatagridRouteImport } from './routes/_authenticated/datagrid'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedGatewaysRouteImport } from './routes/_authenticated/gateways'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedRoutersRouteImport } from './routes/_authenticated/routers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedVouchersRouteImport } from './routes/_authenticated/vouchers'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as AuthenticatedPppoeIndexRouteImport } from './routes/_authenticated/pppoe/index'
import { Route as ApiMikrotikActionRouteImport } from './routes/api/mikrotik/action'
import { Route as ApiPublicCronRouteImport } from './routes/api/public/cron'
import { Route as ApiPublicAgentInstallRouteImport } from './routes/api/public/agent/install'
import { Route as ApiPublicAgentSyncRouteImport } from './routes/api/public/agent/sync'
import { Route as ApiPublicMikrotikOnboardRouteImport } from './routes/api/public/mikrotik/onboard'
import { Route as ApiPublicMikrotikResultRouteImport } from './routes/api/public/mikrotik/result'
import { Route as ApiPublicMikrotikSyncRouteImport } from './routes/api/public/mikrotik/sync'
import { Route as ApiPublicMpesaC2bRouteImport } from './routes/api/public/mpesa/c2b'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatagridRoute = AuthenticatedDatagridRouteImport.update({
  id: '/datagrid',
  path: '/datagrid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGatewaysRoute = AuthenticatedGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutersRoute = AuthenticatedRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVouchersRoute = AuthenticatedVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPppoeIndexRoute = AuthenticatedPppoeIndexRouteImport.update({
  id: '/pppoe/',
  path: '/pppoe/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMikrotikActionRoute = ApiMikrotikActionRouteImport.update({
  id: '/api/mikrotik/action',
  path: '/api/mikrotik/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRoute = ApiPublicCronRouteImport.update({
  id: '/api/public/cron',
  path: '/api/public/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentInstallRoute = ApiPublicAgentInstallRouteImport.update({
  id: '/api/public/agent/install',
  path: '/api/public/agent/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentSyncRoute = ApiPublicAgentSyncRouteImport.update({
  id: '/api/public/agent/sync',
  path: '/api/public/agent/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMikrotikOnboardRoute =
  ApiPublicMikrotikOnboardRouteImport.update({
    id: '/api/public/mikrotik/onboard',
    path: '/api/public/mikrotik/onboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikResultRoute = ApiPublicMikrotikResultRouteImport.update({
  id: '/api/public/mikrotik/result',
  path: '/api/public/mikrotik/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMikrotikSyncRoute = ApiPublicMikrotikSyncRouteImport.update({
  id: '/api/public/mikrotik/sync',
  path: '/api/public/mikrotik/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaC2bRoute = ApiPublicMpesaC2bRouteImport.update({
  id: '/api/public/mpesa/c2b',
  path: '/api/public/mpesa/c2b',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datagrid': typeof AuthenticatedDatagridRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/gateways': typeof AuthenticatedGatewaysRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/routers': typeof AuthenticatedRoutersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/api/mikrotik/action': typeof ApiMikrotikActionRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/pppoe/': typeof AuthenticatedPppoeIndexRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
  '/api/public/mikrotik/onboard': typeof ApiPublicMikrotikOnboardRoute
  '/api/public/mikrotik/result': typeof ApiPublicMikrotikResultRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/mpesa/c2b': typeof ApiPublicMpesaC2bRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datagrid': typeof AuthenticatedDatagridRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/gateways': typeof AuthenticatedGatewaysRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/routers': typeof AuthenticatedRoutersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/api/mikrotik/action': typeof ApiMikrotikActionRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/pppoe': typeof AuthenticatedPppoeIndexRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
  '/api/public/mikrotik/onboard': typeof ApiPublicMikrotikOnboardRoute
  '/api/public/mikrotik/result': typeof ApiPublicMikrotikResultRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/mpesa/c2b': typeof ApiPublicMpesaC2bRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datagrid': typeof AuthenticatedDatagridRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/gateways': typeof AuthenticatedGatewaysRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/routers': typeof AuthenticatedRoutersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/vouchers': typeof AuthenticatedVouchersRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/api/mikrotik/action': typeof ApiMikrotikActionRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/_authenticated/pppoe/': typeof AuthenticatedPppoeIndexRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
  '/api/public/mikrotik/onboard': typeof ApiPublicMikrotikOnboardRoute
  '/api/public/mikrotik/result': typeof ApiPublicMikrotikResultRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/mpesa/c2b': typeof ApiPublicMpesaC2bRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/datagrid'
    | '/devices'
    | '/gateways'
    | '/packages'
    | '/routers'
    | '/settings'
    | '/subscription'
    | '/superadmin'
    | '/transactions'
    | '/vouchers'
    | '/portal/$slug'
    | '/api/mikrotik/action'
    | '/api/public/cron'
    | '/pppoe/'
    | '/api/public/agent/install'
    | '/api/public/agent/sync'
    | '/api/public/mikrotik/onboard'
    | '/api/public/mikrotik/result'
    | '/api/public/mikrotik/sync'
    | '/api/public/mpesa/c2b'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/datagrid'
    | '/devices'
    | '/gateways'
    | '/packages'
    | '/routers'
    | '/settings'
    | '/subscription'
    | '/superadmin'
    | '/transactions'
    | '/vouchers'
    | '/portal/$slug'
    | '/api/mikrotik/action'
    | '/api/public/cron'
    | '/pppoe'
    | '/api/public/agent/install'
    | '/api/public/agent/sync'
    | '/api/public/mikrotik/onboard'
    | '/api/public/mikrotik/result'
    | '/api/public/mikrotik/sync'
    | '/api/public/mpesa/c2b'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/datagrid'
    | '/_authenticated/devices'
    | '/_authenticated/gateways'
    | '/_authenticated/packages'
    | '/_authenticated/routers'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/superadmin'
    | '/_authenticated/transactions'
    | '/_authenticated/vouchers'
    | '/portal/$slug'
    | '/api/mikrotik/action'
    | '/api/public/cron'
    | '/_authenticated/pppoe/'
    | '/api/public/agent/install'
    | '/api/public/agent/sync'
    | '/api/public/mikrotik/onboard'
    | '/api/public/mikrotik/result'
    | '/api/public/mikrotik/sync'
    | '/api/public/mpesa/c2b'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalSlugRoute: typeof PortalSlugRoute
  ApiMikrotikActionRoute: typeof ApiMikrotikActionRoute
  ApiPublicCronRoute: typeof ApiPublicCronRoute
  ApiPublicAgentInstallRoute: typeof ApiPublicAgentInstallRoute
  ApiPublicAgentSyncRoute: typeof ApiPublicAgentSyncRoute
  ApiPublicMikrotikOnboardRoute: typeof ApiPublicMikrotikOnboardRoute
  ApiPublicMikrotikResultRoute: typeof ApiPublicMikrotikResultRoute
  ApiPublicMikrotikSyncRoute: typeof ApiPublicMikrotikSyncRoute
  ApiPublicMpesaC2bRoute: typeof ApiPublicMpesaC2bRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datagrid': {
      id: '/_authenticated/datagrid'
      path: '/datagrid'
      fullPath: '/datagrid'
      preLoaderRoute: typeof AuthenticatedDatagridRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gateways': {
      id: '/_authenticated/gateways'
      path: '/gateways'
      fullPath: '/gateways'
      preLoaderRoute: typeof AuthenticatedGatewaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routers': {
      id: '/_authenticated/routers'
      path: '/routers'
      fullPath: '/routers'
      preLoaderRoute: typeof AuthenticatedRoutersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers': {
      id: '/_authenticated/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthenticatedVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pppoe/': {
      id: '/_authenticated/pppoe/'
      path: '/pppoe'
      fullPath: '/pppoe/'
      preLoaderRoute: typeof AuthenticatedPppoeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/mikrotik/action': {
      id: '/api/mikrotik/action'
      path: '/api/mikrotik/action'
      fullPath: '/api/mikrotik/action'
      preLoaderRoute: typeof ApiMikrotikActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron': {
      id: '/api/public/cron'
      path: '/api/public/cron'
      fullPath: '/api/public/cron'
      preLoaderRoute: typeof ApiPublicCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/install': {
      id: '/api/public/agent/install'
      path: '/api/public/agent/install'
      fullPath: '/api/public/agent/install'
      preLoaderRoute: typeof ApiPublicAgentInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/sync': {
      id: '/api/public/agent/sync'
      path: '/api/public/agent/sync'
      fullPath: '/api/public/agent/sync'
      preLoaderRoute: typeof ApiPublicAgentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/onboard': {
      id: '/api/public/mikrotik/onboard'
      path: '/api/public/mikrotik/onboard'
      fullPath: '/api/public/mikrotik/onboard'
      preLoaderRoute: typeof ApiPublicMikrotikOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/result': {
      id: '/api/public/mikrotik/result'
      path: '/api/public/mikrotik/result'
      fullPath: '/api/public/mikrotik/result'
      preLoaderRoute: typeof ApiPublicMikrotikResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/sync': {
      id: '/api/public/mikrotik/sync'
      path: '/api/public/mikrotik/sync'
      fullPath: '/api/public/mikrotik/sync'
      preLoaderRoute: typeof ApiPublicMikrotikSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/c2b': {
      id: '/api/public/mpesa/c2b'
      path: '/api/public/mpesa/c2b'
      fullPath: '/api/public/mpesa/c2b'
      preLoaderRoute: typeof ApiPublicMpesaC2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatagridRoute: typeof AuthenticatedDatagridRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedGatewaysRoute: typeof AuthenticatedGatewaysRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedRoutersRoute: typeof AuthenticatedRoutersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedVouchersRoute: typeof AuthenticatedVouchersRoute
  AuthenticatedPppoeIndexRoute: typeof AuthenticatedPppoeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatagridRoute: AuthenticatedDatagridRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedGatewaysRoute: AuthenticatedGatewaysRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedRoutersRoute: AuthenticatedRoutersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedVouchersRoute: AuthenticatedVouchersRoute,
  AuthenticatedPppoeIndexRoute: AuthenticatedPppoeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalSlugRoute: PortalSlugRoute,
  ApiMikrotikActionRoute: ApiMikrotikActionRoute,
  ApiPublicCronRoute: ApiPublicCronRoute,
  ApiPublicAgentInstallRoute: ApiPublicAgentInstallRoute,
  ApiPublicAgentSyncRoute: ApiPublicAgentSyncRoute,
  ApiPublicMikrotikOnboardRoute: ApiPublicMikrotikOnboardRoute,
  ApiPublicMikrotikResultRoute: ApiPublicMikrotikResultRoute,
  ApiPublicMikrotikSyncRoute: ApiPublicMikrotikSyncRoute,
  ApiPublicMpesaC2bRoute: ApiPublicMpesaC2bRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
