/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiOperationsRouteImport } from './routes/_authenticated/ai-operations'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDatagridRouteImport } from './routes/_authenticated/datagrid'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedGatewaysRouteImport } from './routes/_authenticated/gateways'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedRoutersRouteImport } from './routes/_authenticated/routers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedVouchersRouteImport } from './routes/_authenticated/vouchers'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as AuthenticatedPppoeIndexRouteImport } from './routes/_authenticated/pppoe/index'
import { Route as ApiMikrotikActionRouteImport } from './routes/api/mikrotik/action'
import { Route as ApiPublicConfigRouteImport } from './routes/api/public/config'
import { Route as ApiPublicCronRouteImport } from './routes/api/public/cron'
import { Route as ApiPublicPortalValidateRouteImport } from './routes/api/public/portal-validate'
import { Route as ApiPublicAgentInstallRouteImport } from './routes/api/public/agent/install'
import { Route as ApiPublicAgentSyncRouteImport } from './routes/api/public/agent/sync'
import { Route as ApiPublicMikrotikConfigRouteImport } from './routes/api/public/mikrotik/config'
import { Route as ApiPublicMikrotikConfigResultRouteImport } from './routes/api/public/mikrotik/config-result'
import { Route as ApiPublicMikrotikHeartbeatRouteImport } from './routes/api/public/mikrotik/heartbeat'
import { Route as ApiPublicMikrotikOnboardRouteImport } from './routes/api/public/mikrotik/onboard'
import { Route as ApiPublicMikrotikPortalFileRouteImport } from './routes/api/public/mikrotik/portal-file'
import { Route as ApiPublicMikrotikRegisterRouteImport } from './routes/api/public/mikrotik/register'
import { Route as ApiPublicMikrotikScanReportRouteImport } from './routes/api/public/mikrotik/scan-report'
import { Route as ApiPublicMikrotikSupabaseCallbackRouteImport } from './routes/api/public/mikrotik/supabase-callback'
import { Route as ApiPublicMikrotikSyncRouteImport } from './routes/api/public/mikrotik/sync'
import { Route as ApiPublicMikrotikSyncsourceRouteImport } from './routes/api/public/mikrotik/syncsource'
import { Route as ApiPublicMikrotikWebhookRouteImport } from './routes/api/public/mikrotik/webhook'
import { Route as ApiPublicMpesaC2bRouteImport } from './routes/api/public/mpesa/c2b'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'
import { Route as ApiPublicMikrotikOnboardTokenRouteImport } from './routes/api/public/mikrotik/onboard.$token'
import { Route as ApiPublicMikrotikPortalFileTokenFileRouteImport } from './routes/api/public/mikrotik/portal-file.$token.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiOperationsRoute =
  AuthenticatedAiOperationsRouteImport.update({
    id: '/ai-operations',
    path: '/ai-operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatagridRoute = AuthenticatedDatagridRouteImport.update({
  id: '/datagrid',
  path: '/datagrid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGatewaysRoute = AuthenticatedGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutersRoute = AuthenticatedRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVouchersRoute = AuthenticatedVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPppoeIndexRoute = AuthenticatedPppoeIndexRouteImport.update({
  id: '/pppoe/',
  path: '/pppoe/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMikrotikActionRoute = ApiMikrotikActionRouteImport.update({
  id: '/api/mikrotik/action',
  path: '/api/mikrotik/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public/config',
  path: '/api/public/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRoute = ApiPublicCronRouteImport.update({
  id: '/api/public/cron',
  path: '/api/public/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalValidateRoute = ApiPublicPortalValidateRouteImport.update({
  id: '/api/public/portal-validate',
  path: '/api/public/portal-validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentInstallRoute = ApiPublicAgentInstallRouteImport.update({
  id: '/api/public/agent/install',
  path: '/api/public/agent/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentSyncRoute = ApiPublicAgentSyncRouteImport.update({
  id: '/api/public/agent/sync',
  path: '/api/public/agent/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMikrotikConfigRoute = ApiPublicMikrotikConfigRouteImport.update({
  id: '/api/public/mikrotik/config',
  path: '/api/public/mikrotik/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMikrotikConfigResultRoute =
  ApiPublicMikrotikConfigResultRouteImport.update({
    id: '/api/public/mikrotik/config-result',
    path: '/api/public/mikrotik/config-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikHeartbeatRoute =
  ApiPublicMikrotikHeartbeatRouteImport.update({
    id: '/api/public/mikrotik/heartbeat',
    path: '/api/public/mikrotik/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikOnboardRoute =
  ApiPublicMikrotikOnboardRouteImport.update({
    id: '/api/public/mikrotik/onboard',
    path: '/api/public/mikrotik/onboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikPortalFileRoute =
  ApiPublicMikrotikPortalFileRouteImport.update({
    id: '/api/public/mikrotik/portal-file',
    path: '/api/public/mikrotik/portal-file',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikRegisterRoute =
  ApiPublicMikrotikRegisterRouteImport.update({
    id: '/api/public/mikrotik/register',
    path: '/api/public/mikrotik/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikScanReportRoute =
  ApiPublicMikrotikScanReportRouteImport.update({
    id: '/api/public/mikrotik/scan-report',
    path: '/api/public/mikrotik/scan-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikSupabaseCallbackRoute =
  ApiPublicMikrotikSupabaseCallbackRouteImport.update({
    id: '/api/public/mikrotik/supabase-callback',
    path: '/api/public/mikrotik/supabase-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikSyncRoute = ApiPublicMikrotikSyncRouteImport.update({
  id: '/api/public/mikrotik/sync',
  path: '/api/public/mikrotik/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMikrotikSyncsourceRoute =
  ApiPublicMikrotikSyncsourceRouteImport.update({
    id: '/api/public/mikrotik/syncsource',
    path: '/api/public/mikrotik/syncsource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMikrotikWebhookRoute =
  ApiPublicMikrotikWebhookRouteImport.update({
    id: '/api/public/mikrotik/webhook',
    path: '/api/public/mikrotik/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaC2bRoute = ApiPublicMpesaC2bRouteImport.update({
  id: '/api/public/mpesa/c2b',
  path: '/api/public/mpesa/c2b',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMikrotikOnboardTokenRoute =
  ApiPublicMikrotikOnboardTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => ApiPublicMikrotikOnboardRoute,
  } as any)
const ApiPublicMikrotikPortalFileTokenFileRoute =
  ApiPublicMikrotikPortalFileTokenFileRouteImport.update({
    id: '/$token/$file',
    path: '/$token/$file',
    getParentRoute: () => ApiPublicMikrotikPortalFileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-operations': typeof AuthenticatedAiOperationsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datagrid': typeof AuthenticatedDatagridRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/gateways': typeof AuthenticatedGatewaysRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/routers': typeof AuthenticatedRoutersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/api/health': typeof ApiHealthRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/api/mikrotik/action': typeof ApiMikrotikActionRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/portal-validate': typeof ApiPublicPortalValidateRoute
  '/pppoe/': typeof AuthenticatedPppoeIndexRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
  '/api/public/mikrotik/config': typeof ApiPublicMikrotikConfigRoute
  '/api/public/mikrotik/config-result': typeof ApiPublicMikrotikConfigResultRoute
  '/api/public/mikrotik/heartbeat': typeof ApiPublicMikrotikHeartbeatRoute
  '/api/public/mikrotik/onboard': typeof ApiPublicMikrotikOnboardRouteWithChildren
  '/api/public/mikrotik/portal-file': typeof ApiPublicMikrotikPortalFileRouteWithChildren
  '/api/public/mikrotik/register': typeof ApiPublicMikrotikRegisterRoute
  '/api/public/mikrotik/scan-report': typeof ApiPublicMikrotikScanReportRoute
  '/api/public/mikrotik/supabase-callback': typeof ApiPublicMikrotikSupabaseCallbackRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/mikrotik/syncsource': typeof ApiPublicMikrotikSyncsourceRoute
  '/api/public/mikrotik/webhook': typeof ApiPublicMikrotikWebhookRoute
  '/api/public/mpesa/c2b': typeof ApiPublicMpesaC2bRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/mikrotik/onboard/$token': typeof ApiPublicMikrotikOnboardTokenRoute
  '/api/public/mikrotik/portal-file/$token/$file': typeof ApiPublicMikrotikPortalFileTokenFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-operations': typeof AuthenticatedAiOperationsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datagrid': typeof AuthenticatedDatagridRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/gateways': typeof AuthenticatedGatewaysRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/routers': typeof AuthenticatedRoutersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/api/health': typeof ApiHealthRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/api/mikrotik/action': typeof ApiMikrotikActionRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/portal-validate': typeof ApiPublicPortalValidateRoute
  '/pppoe': typeof AuthenticatedPppoeIndexRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
  '/api/public/mikrotik/config': typeof ApiPublicMikrotikConfigRoute
  '/api/public/mikrotik/config-result': typeof ApiPublicMikrotikConfigResultRoute
  '/api/public/mikrotik/heartbeat': typeof ApiPublicMikrotikHeartbeatRoute
  '/api/public/mikrotik/onboard': typeof ApiPublicMikrotikOnboardRouteWithChildren
  '/api/public/mikrotik/portal-file': typeof ApiPublicMikrotikPortalFileRouteWithChildren
  '/api/public/mikrotik/register': typeof ApiPublicMikrotikRegisterRoute
  '/api/public/mikrotik/scan-report': typeof ApiPublicMikrotikScanReportRoute
  '/api/public/mikrotik/supabase-callback': typeof ApiPublicMikrotikSupabaseCallbackRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/mikrotik/syncsource': typeof ApiPublicMikrotikSyncsourceRoute
  '/api/public/mikrotik/webhook': typeof ApiPublicMikrotikWebhookRoute
  '/api/public/mpesa/c2b': typeof ApiPublicMpesaC2bRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/mikrotik/onboard/$token': typeof ApiPublicMikrotikOnboardTokenRoute
  '/api/public/mikrotik/portal-file/$token/$file': typeof ApiPublicMikrotikPortalFileTokenFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-operations': typeof AuthenticatedAiOperationsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datagrid': typeof AuthenticatedDatagridRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/gateways': typeof AuthenticatedGatewaysRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/routers': typeof AuthenticatedRoutersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/vouchers': typeof AuthenticatedVouchersRoute
  '/api/health': typeof ApiHealthRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/api/mikrotik/action': typeof ApiMikrotikActionRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/public/cron': typeof ApiPublicCronRoute
  '/api/public/portal-validate': typeof ApiPublicPortalValidateRoute
  '/_authenticated/pppoe/': typeof AuthenticatedPppoeIndexRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/sync': typeof ApiPublicAgentSyncRoute
  '/api/public/mikrotik/config': typeof ApiPublicMikrotikConfigRoute
  '/api/public/mikrotik/config-result': typeof ApiPublicMikrotikConfigResultRoute
  '/api/public/mikrotik/heartbeat': typeof ApiPublicMikrotikHeartbeatRoute
  '/api/public/mikrotik/onboard': typeof ApiPublicMikrotikOnboardRouteWithChildren
  '/api/public/mikrotik/portal-file': typeof ApiPublicMikrotikPortalFileRouteWithChildren
  '/api/public/mikrotik/register': typeof ApiPublicMikrotikRegisterRoute
  '/api/public/mikrotik/scan-report': typeof ApiPublicMikrotikScanReportRoute
  '/api/public/mikrotik/supabase-callback': typeof ApiPublicMikrotikSupabaseCallbackRoute
  '/api/public/mikrotik/sync': typeof ApiPublicMikrotikSyncRoute
  '/api/public/mikrotik/syncsource': typeof ApiPublicMikrotikSyncsourceRoute
  '/api/public/mikrotik/webhook': typeof ApiPublicMikrotikWebhookRoute
  '/api/public/mpesa/c2b': typeof ApiPublicMpesaC2bRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
  '/api/public/mikrotik/onboard/$token': typeof ApiPublicMikrotikOnboardTokenRoute
  '/api/public/mikrotik/portal-file/$token/$file': typeof ApiPublicMikrotikPortalFileTokenFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/ai-operations'
    | '/customers'
    | '/dashboard'
    | '/datagrid'
    | '/devices'
    | '/gateways'
    | '/packages'
    | '/routers'
    | '/settings'
    | '/subscription'
    | '/superadmin'
    | '/transactions'
    | '/vouchers'
    | '/api/health'
    | '/portal/$slug'
    | '/api/mikrotik/action'
    | '/api/public/config'
    | '/api/public/cron'
    | '/api/public/portal-validate'
    | '/pppoe/'
    | '/api/public/agent/install'
    | '/api/public/agent/sync'
    | '/api/public/mikrotik/config'
    | '/api/public/mikrotik/config-result'
    | '/api/public/mikrotik/heartbeat'
    | '/api/public/mikrotik/onboard'
    | '/api/public/mikrotik/portal-file'
    | '/api/public/mikrotik/register'
    | '/api/public/mikrotik/scan-report'
    | '/api/public/mikrotik/supabase-callback'
    | '/api/public/mikrotik/sync'
    | '/api/public/mikrotik/syncsource'
    | '/api/public/mikrotik/webhook'
    | '/api/public/mpesa/c2b'
    | '/api/public/mpesa/callback'
    | '/api/public/mikrotik/onboard/$token'
    | '/api/public/mikrotik/portal-file/$token/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/ai-operations'
    | '/customers'
    | '/dashboard'
    | '/datagrid'
    | '/devices'
    | '/gateways'
    | '/packages'
    | '/routers'
    | '/settings'
    | '/subscription'
    | '/superadmin'
    | '/transactions'
    | '/vouchers'
    | '/api/health'
    | '/portal/$slug'
    | '/api/mikrotik/action'
    | '/api/public/config'
    | '/api/public/cron'
    | '/api/public/portal-validate'
    | '/pppoe'
    | '/api/public/agent/install'
    | '/api/public/agent/sync'
    | '/api/public/mikrotik/config'
    | '/api/public/mikrotik/config-result'
    | '/api/public/mikrotik/heartbeat'
    | '/api/public/mikrotik/onboard'
    | '/api/public/mikrotik/portal-file'
    | '/api/public/mikrotik/register'
    | '/api/public/mikrotik/scan-report'
    | '/api/public/mikrotik/supabase-callback'
    | '/api/public/mikrotik/sync'
    | '/api/public/mikrotik/syncsource'
    | '/api/public/mikrotik/webhook'
    | '/api/public/mpesa/c2b'
    | '/api/public/mpesa/callback'
    | '/api/public/mikrotik/onboard/$token'
    | '/api/public/mikrotik/portal-file/$token/$file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/ai-operations'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/datagrid'
    | '/_authenticated/devices'
    | '/_authenticated/gateways'
    | '/_authenticated/packages'
    | '/_authenticated/routers'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/superadmin'
    | '/_authenticated/transactions'
    | '/_authenticated/vouchers'
    | '/api/health'
    | '/portal/$slug'
    | '/api/mikrotik/action'
    | '/api/public/config'
    | '/api/public/cron'
    | '/api/public/portal-validate'
    | '/_authenticated/pppoe/'
    | '/api/public/agent/install'
    | '/api/public/agent/sync'
    | '/api/public/mikrotik/config'
    | '/api/public/mikrotik/config-result'
    | '/api/public/mikrotik/heartbeat'
    | '/api/public/mikrotik/onboard'
    | '/api/public/mikrotik/portal-file'
    | '/api/public/mikrotik/register'
    | '/api/public/mikrotik/scan-report'
    | '/api/public/mikrotik/supabase-callback'
    | '/api/public/mikrotik/sync'
    | '/api/public/mikrotik/syncsource'
    | '/api/public/mikrotik/webhook'
    | '/api/public/mpesa/c2b'
    | '/api/public/mpesa/callback'
    | '/api/public/mikrotik/onboard/$token'
    | '/api/public/mikrotik/portal-file/$token/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PortalSlugRoute: typeof PortalSlugRoute
  ApiMikrotikActionRoute: typeof ApiMikrotikActionRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
  ApiPublicCronRoute: typeof ApiPublicCronRoute
  ApiPublicPortalValidateRoute: typeof ApiPublicPortalValidateRoute
  ApiPublicAgentInstallRoute: typeof ApiPublicAgentInstallRoute
  ApiPublicAgentSyncRoute: typeof ApiPublicAgentSyncRoute
  ApiPublicMikrotikConfigRoute: typeof ApiPublicMikrotikConfigRoute
  ApiPublicMikrotikConfigResultRoute: typeof ApiPublicMikrotikConfigResultRoute
  ApiPublicMikrotikHeartbeatRoute: typeof ApiPublicMikrotikHeartbeatRoute
  ApiPublicMikrotikOnboardRoute: typeof ApiPublicMikrotikOnboardRouteWithChildren
  ApiPublicMikrotikPortalFileRoute: typeof ApiPublicMikrotikPortalFileRouteWithChildren
  ApiPublicMikrotikRegisterRoute: typeof ApiPublicMikrotikRegisterRoute
  ApiPublicMikrotikScanReportRoute: typeof ApiPublicMikrotikScanReportRoute
  ApiPublicMikrotikSupabaseCallbackRoute: typeof ApiPublicMikrotikSupabaseCallbackRoute
  ApiPublicMikrotikSyncRoute: typeof ApiPublicMikrotikSyncRoute
  ApiPublicMikrotikSyncsourceRoute: typeof ApiPublicMikrotikSyncsourceRoute
  ApiPublicMikrotikWebhookRoute: typeof ApiPublicMikrotikWebhookRoute
  ApiPublicMpesaC2bRoute: typeof ApiPublicMpesaC2bRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-operations': {
      id: '/_authenticated/ai-operations'
      path: '/ai-operations'
      fullPath: '/ai-operations'
      preLoaderRoute: typeof AuthenticatedAiOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datagrid': {
      id: '/_authenticated/datagrid'
      path: '/datagrid'
      fullPath: '/datagrid'
      preLoaderRoute: typeof AuthenticatedDatagridRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gateways': {
      id: '/_authenticated/gateways'
      path: '/gateways'
      fullPath: '/gateways'
      preLoaderRoute: typeof AuthenticatedGatewaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routers': {
      id: '/_authenticated/routers'
      path: '/routers'
      fullPath: '/routers'
      preLoaderRoute: typeof AuthenticatedRoutersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers': {
      id: '/_authenticated/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthenticatedVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pppoe/': {
      id: '/_authenticated/pppoe/'
      path: '/pppoe'
      fullPath: '/pppoe/'
      preLoaderRoute: typeof AuthenticatedPppoeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/mikrotik/action': {
      id: '/api/mikrotik/action'
      path: '/api/mikrotik/action'
      fullPath: '/api/mikrotik/action'
      preLoaderRoute: typeof ApiMikrotikActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/config': {
      id: '/api/public/config'
      path: '/api/public/config'
      fullPath: '/api/public/config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron': {
      id: '/api/public/cron'
      path: '/api/public/cron'
      fullPath: '/api/public/cron'
      preLoaderRoute: typeof ApiPublicCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal-validate': {
      id: '/api/public/portal-validate'
      path: '/api/public/portal-validate'
      fullPath: '/api/public/portal-validate'
      preLoaderRoute: typeof ApiPublicPortalValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/install': {
      id: '/api/public/agent/install'
      path: '/api/public/agent/install'
      fullPath: '/api/public/agent/install'
      preLoaderRoute: typeof ApiPublicAgentInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/sync': {
      id: '/api/public/agent/sync'
      path: '/api/public/agent/sync'
      fullPath: '/api/public/agent/sync'
      preLoaderRoute: typeof ApiPublicAgentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/config': {
      id: '/api/public/mikrotik/config'
      path: '/api/public/mikrotik/config'
      fullPath: '/api/public/mikrotik/config'
      preLoaderRoute: typeof ApiPublicMikrotikConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/config-result': {
      id: '/api/public/mikrotik/config-result'
      path: '/api/public/mikrotik/config-result'
      fullPath: '/api/public/mikrotik/config-result'
      preLoaderRoute: typeof ApiPublicMikrotikConfigResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/heartbeat': {
      id: '/api/public/mikrotik/heartbeat'
      path: '/api/public/mikrotik/heartbeat'
      fullPath: '/api/public/mikrotik/heartbeat'
      preLoaderRoute: typeof ApiPublicMikrotikHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/onboard': {
      id: '/api/public/mikrotik/onboard'
      path: '/api/public/mikrotik/onboard'
      fullPath: '/api/public/mikrotik/onboard'
      preLoaderRoute: typeof ApiPublicMikrotikOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/portal-file': {
      id: '/api/public/mikrotik/portal-file'
      path: '/api/public/mikrotik/portal-file'
      fullPath: '/api/public/mikrotik/portal-file'
      preLoaderRoute: typeof ApiPublicMikrotikPortalFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/register': {
      id: '/api/public/mikrotik/register'
      path: '/api/public/mikrotik/register'
      fullPath: '/api/public/mikrotik/register'
      preLoaderRoute: typeof ApiPublicMikrotikRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/scan-report': {
      id: '/api/public/mikrotik/scan-report'
      path: '/api/public/mikrotik/scan-report'
      fullPath: '/api/public/mikrotik/scan-report'
      preLoaderRoute: typeof ApiPublicMikrotikScanReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/supabase-callback': {
      id: '/api/public/mikrotik/supabase-callback'
      path: '/api/public/mikrotik/supabase-callback'
      fullPath: '/api/public/mikrotik/supabase-callback'
      preLoaderRoute: typeof ApiPublicMikrotikSupabaseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/sync': {
      id: '/api/public/mikrotik/sync'
      path: '/api/public/mikrotik/sync'
      fullPath: '/api/public/mikrotik/sync'
      preLoaderRoute: typeof ApiPublicMikrotikSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/syncsource': {
      id: '/api/public/mikrotik/syncsource'
      path: '/api/public/mikrotik/syncsource'
      fullPath: '/api/public/mikrotik/syncsource'
      preLoaderRoute: typeof ApiPublicMikrotikSyncsourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/webhook': {
      id: '/api/public/mikrotik/webhook'
      path: '/api/public/mikrotik/webhook'
      fullPath: '/api/public/mikrotik/webhook'
      preLoaderRoute: typeof ApiPublicMikrotikWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/c2b': {
      id: '/api/public/mpesa/c2b'
      path: '/api/public/mpesa/c2b'
      fullPath: '/api/public/mpesa/c2b'
      preLoaderRoute: typeof ApiPublicMpesaC2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mikrotik/onboard/$token': {
      id: '/api/public/mikrotik/onboard/$token'
      path: '/$token'
      fullPath: '/api/public/mikrotik/onboard/$token'
      preLoaderRoute: typeof ApiPublicMikrotikOnboardTokenRouteImport
      parentRoute: typeof ApiPublicMikrotikOnboardRoute
    }
    '/api/public/mikrotik/portal-file/$token/$file': {
      id: '/api/public/mikrotik/portal-file/$token/$file'
      path: '/$token/$file'
      fullPath: '/api/public/mikrotik/portal-file/$token/$file'
      preLoaderRoute: typeof ApiPublicMikrotikPortalFileTokenFileRouteImport
      parentRoute: typeof ApiPublicMikrotikPortalFileRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiOperationsRoute: typeof AuthenticatedAiOperationsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatagridRoute: typeof AuthenticatedDatagridRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedGatewaysRoute: typeof AuthenticatedGatewaysRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedRoutersRoute: typeof AuthenticatedRoutersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedVouchersRoute: typeof AuthenticatedVouchersRoute
  AuthenticatedPppoeIndexRoute: typeof AuthenticatedPppoeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiOperationsRoute: AuthenticatedAiOperationsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatagridRoute: AuthenticatedDatagridRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedGatewaysRoute: AuthenticatedGatewaysRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedRoutersRoute: AuthenticatedRoutersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedVouchersRoute: AuthenticatedVouchersRoute,
  AuthenticatedPppoeIndexRoute: AuthenticatedPppoeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicMikrotikOnboardRouteChildren {
  ApiPublicMikrotikOnboardTokenRoute: typeof ApiPublicMikrotikOnboardTokenRoute
}

const ApiPublicMikrotikOnboardRouteChildren: ApiPublicMikrotikOnboardRouteChildren =
  {
    ApiPublicMikrotikOnboardTokenRoute: ApiPublicMikrotikOnboardTokenRoute,
  }

const ApiPublicMikrotikOnboardRouteWithChildren =
  ApiPublicMikrotikOnboardRoute._addFileChildren(
    ApiPublicMikrotikOnboardRouteChildren,
  )

interface ApiPublicMikrotikPortalFileRouteChildren {
  ApiPublicMikrotikPortalFileTokenFileRoute: typeof ApiPublicMikrotikPortalFileTokenFileRoute
}

const ApiPublicMikrotikPortalFileRouteChildren: ApiPublicMikrotikPortalFileRouteChildren =
  {
    ApiPublicMikrotikPortalFileTokenFileRoute:
      ApiPublicMikrotikPortalFileTokenFileRoute,
  }

const ApiPublicMikrotikPortalFileRouteWithChildren =
  ApiPublicMikrotikPortalFileRoute._addFileChildren(
    ApiPublicMikrotikPortalFileRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthRoute: ApiHealthRoute,
  PortalSlugRoute: PortalSlugRoute,
  ApiMikrotikActionRoute: ApiMikrotikActionRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
  ApiPublicCronRoute: ApiPublicCronRoute,
  ApiPublicPortalValidateRoute: ApiPublicPortalValidateRoute,
  ApiPublicAgentInstallRoute: ApiPublicAgentInstallRoute,
  ApiPublicAgentSyncRoute: ApiPublicAgentSyncRoute,
  ApiPublicMikrotikConfigRoute: ApiPublicMikrotikConfigRoute,
  ApiPublicMikrotikConfigResultRoute: ApiPublicMikrotikConfigResultRoute,
  ApiPublicMikrotikHeartbeatRoute: ApiPublicMikrotikHeartbeatRoute,
  ApiPublicMikrotikOnboardRoute: ApiPublicMikrotikOnboardRouteWithChildren,
  ApiPublicMikrotikPortalFileRoute:
    ApiPublicMikrotikPortalFileRouteWithChildren,
  ApiPublicMikrotikRegisterRoute: ApiPublicMikrotikRegisterRoute,
  ApiPublicMikrotikScanReportRoute: ApiPublicMikrotikScanReportRoute,
  ApiPublicMikrotikSupabaseCallbackRoute:
    ApiPublicMikrotikSupabaseCallbackRoute,
  ApiPublicMikrotikSyncRoute: ApiPublicMikrotikSyncRoute,
  ApiPublicMikrotikSyncsourceRoute: ApiPublicMikrotikSyncsourceRoute,
  ApiPublicMikrotikWebhookRoute: ApiPublicMikrotikWebhookRoute,
  ApiPublicMpesaC2bRoute: ApiPublicMpesaC2bRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
