// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types.ts";
import { brokeredPreviewStorage } from "./previewAuthStorage.ts";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function normalizeSupabaseUrl(url: string): string {
  let trimmed = url.trim();
  if (!trimmed) return "";
  if (!trimmed.startsWith("http://") && !trimmed.startsWith("https://")) {
    trimmed = `https://${trimmed}`;
  }
  return trimmed.replace(/\/+$/, "");
}

let _supabase: ReturnType<typeof createClient<Database>> | undefined;
let _lastConfigKey = "";

function getSupabaseClient() {
  const winConfig =
    typeof window !== "undefined"
      ? (
          window as unknown as {
            __PUBLIC_CONFIG__?: { supabaseUrl?: string; supabasePublishableKey?: string };
          }
        ).__PUBLIC_CONFIG__
      : undefined;

  const urlCandidate =
    winConfig?.supabaseUrl ||
    (typeof import.meta !== "undefined" && import.meta.env?.["VITE_SUPABASE_URL"]) ||
    (typeof process !== "undefined" &&
      (process.env?.["SUPABASE_URL"] || process.env?.["VITE_SUPABASE_URL"])) ||
    "";

  const keyCandidate =
    winConfig?.supabasePublishableKey ||
    (typeof import.meta !== "undefined" && import.meta.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"]) ||
    (typeof process !== "undefined" &&
      (process.env?.["SUPABASE_PUBLISHABLE_KEY"] ||
        process.env?.["VITE_SUPABASE_PUBLISHABLE_KEY"])) ||
    "";

  const rawUrl = normalizeSupabaseUrl(urlCandidate);
  const activeKey = keyCandidate.trim() || "placeholder-key";
  const activeUrl = rawUrl || "https://placeholder.supabase.co";

  const currentConfigKey = `${activeUrl}::${activeKey}`;

  // If in browser and config is still placeholder, auto-fetch from /api/public/config
  if (typeof window !== "undefined" && (!rawUrl || rawUrl === "https://placeholder.supabase.co")) {
    const win = window as unknown as {
      __fetchingSupabaseConfig?: boolean;
      __PUBLIC_CONFIG__?: { supabaseUrl?: string; supabasePublishableKey?: string };
    };
    if (!win.__fetchingSupabaseConfig) {
      win.__fetchingSupabaseConfig = true;
      fetch("/api/public/config")
        .then((res) => (res.ok ? res.json() : null))
        .then((data) => {
          if (data?.supabaseUrl && data?.supabasePublishableKey) {
            win.__PUBLIC_CONFIG__ = {
              supabaseUrl: data.supabaseUrl,
              supabasePublishableKey: data.supabasePublishableKey,
            };
            _lastConfigKey = "";
            getSupabaseClient();
          }
        })
        .catch(() => {});
    }
  }

  if (_supabase && _lastConfigKey === currentConfigKey) {
    return _supabase;
  }

  // If previous client was placeholder and we now have real credentials, reinitialize
  _lastConfigKey = currentConfigKey;
  _supabase = createClient<Database>(activeUrl, activeKey, {
    global: {
      fetch: createSupabaseFetch(activeKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop, receiver) {
    const client = getSupabaseClient();
    return Reflect.get(client, prop, receiver);
  },
});
